- client/components/cart.js
---
Created a React component where our shopping cart will eventually be viewed
> feature: initialized the cart component

- .travis.yml
- package.json
[ ] updated package.json name and description
[ ] updated before-script database name in travis.yml
---
I updated the package.json and the travis.yml files to reflect our app name as graceshopper
> updated package name, description, and db name to graceshopper

- server/db/models/index.js
- server/db/models/order.js
- server/db/models/plant.js
- server/db/models/user.js
---
* I initialized models for User (very similar to boilermakers), Plant, and Order (closes #4)
* made one-to-many associations for users and orders, and many-to-many for plants and orders
> initial model definitions for User, Plant, Order

- script/seed.js
- server/db/models/index.js
changed seed file to update fake orders with checkedOut: true and items: [] being an array of Integers
> updated seed file

- package-lock.json
- package.json
- server/db/models/index.js
- server/db/models/order.js
---
I re-added the checkedOut boolean to the order model, and updated the associations in model/index.js as per our meeting
> updated associations and re-added checkedOut boolean to order model

- server/api/orders.js
> changed import to require on order api

- client/components/navbar.js
- public/index.html
approve of title/name change from boilermaker to 'The Octopus' Garden'
> changed from boilermaker to the octopus garden

- test/setup.js
- test/tier-1.js
---
4:17pm, Tuesday Sept 17
I made a directory for our tests but haven't yet modified the packages.json or gotten mocha working, will return to this shortly!
> added a test directory

- client/components/navbar.js
- client/store/cart.js
- server/api/orders.js
- server/api/orders.js.rej
---
Hey, I worked on this tonight after class, as mentioned during our last standup. I wrote additional API routes for orders, which apply to the cart as well. I included comments mentioning the purpose of each route for your review. Thanks!
> added api routes for orders + cart

- server/api/orders.js
> fix: userId on order api route

- client/components/SinglePlant.js
- client/components/SinglePlantView.js
- client/components/navbar.js
- public/style.css
simple button added and simple handleSubmit function added to singlePlant and singlePlantView components
> feat: button for single plants to add to cart

- server/api/orders.js
- server/db/models/index.js
eager load plants on order api
> feat: eager loaded plant model on order

- client/components/cart.js
- client/components/order-form.js
- client/routes.js
- client/store/order.js
-order form in cart component (right now, both for empty and full carts)
-able to put request to order (BUT hardcoded order1 for now???)
> feat: rendered order form in cart component

- test/tier-1.js
---
The framework for testing models and routes has been set up as well.
> wrote 2 tests for checking API routes ('tier 1: see all products')

- client/components/SingleCartItem.js
- client/components/cart.js
---
Hey all, I realized that I forgot to do a pull request for the work we did together yesterday. If someone can merge approve and merge this pull requests so we're all pulling from the same master, that would be great! Thank you.
> merged cart component, ensured that checkout works

- README.md
- client/components/navbar.js
Updated the README.md with a link to our team page and a brief description. 
closes #40
> documentation: Updated README.md with accurate info

- client/store/cart.js
- server/api/orders.js
Clear cart now works!  I accomplished this by deleting the rows in PlantOrder and just making a new cart with the same userId, etc, after the cart has been cleared. 
closes #56
> fix: fixed bug where cart will have old items in it

- README.md
Updated README as per Martha's suggestions!
> documentation: added technologies and getting started to README

- test/tier-1.js
Just aligned some braces and parentheses in the testing file after merging Casey's commits! 
See the other pull request for details as to what still needs to be fixed, but good job team!
> fix: minor bugs (aligning brackets)

- test/order.spec.js
- test/tier-1.js
Added two test specs for order Models.
> #41 order form

- script/seed.js
- server/api/index.js
- server/api/orders.js
- server/db/models/user.js
- server/index.js
- server/permission.js
still need to create control flow to account for req.user to be able to make get and put requests on their own order
> feat: user and order api route visible only to admin 

- client/components/SinglePlant.js
- client/store/cart.js
- server/api/orders.js
- server/auth/index.js
- server/db/models/user.js
- [X} edited createCart, addItemtoCart
--
Still dealing with some bugs. Please merge so we can all pull from the same.
> #58 code cleanup

- server/api/users.js
> fix: added role back to attributes

- client/components/SingleCartItem.js
- client/components/SinglePlant.js
- client/components/cart.js
- client/store/cart.js
- server/api/orders.js
addItem works
cart displays with req.sessions
> #58 code cleanup continued

- client/components/confirmationForm.js
> #41_order_form

- client/components/SingleCartItem.js
- client/components/SinglePlant.js
- client/store/cart.js
> feat: remove item button in progress

- client/app.js
- client/store/cart.js
- server/api/orders.js
- server/index.js
session persists for user and guest - user can browse as guest and cart persists after login
session cookies have maxage and expiration after 3 hours
> fix: session persists for user and guest

- client/components/confirmationForm.js
Fixed error in confirmation Form. Added total cost.
> fix:confirmationForm

- client/components/user-home.js
- client/store/order.js
- server/api/users.js
really ugly homepage BUT it has the user's order history!
> feat: rudimentary order history view upon login

- client/components/SinglePlant.js
- client/components/navbar.js
- client/components/splash.js
- public/index.html
- public/style.css
- server/api/orders.js
---
I added styling to splash, navbar, add buttons. Forms still need work. Cart display, all plants, and single plant still need formatting. I expect there to be conflicts with this request (I was unable to pull origin master due to some already)...
I formatted this on my desktop at home, which has a huge screen/wide resolution. Hopefully it translates well onto smaller screens (ala flex), but I haven't been able to test that.
I also removed async from some of our routes (since req.session does not make calls to the database, there's no need for these).
> #81 design

- client/store/cart.js
- server/api/orders.js
- NO MORE DUPLICATES!!!! However, there are bugs. The state shows the correct orderQty per plantOrder object, but the component does not.
- GetCart() is being called in an infinite loop after clearing.
- I changed the Add Item POST route to return the whole cart rather than just the last item in the array, and now the thunk calls getCart with that new data (to retrieve the updated cart array), since this will accommodate getting plants with updated order quantities.
... goodnight!
> #57 remove dupes

- client/components/cart.js
- client/components/order-form.js
- server/api/orders.js
> #82 group edit

- client/components/SingleCartItem.js
- client/components/cart.js
- client/components/confirmationForm.js
- client/components/order-form.js
- client/components/user-home.js
- client/store/order.js
- server/api/orders.js
> #82 fix checkout

- client/store/cart.js
- server/api/orders.js
> fix: alter req.session with edit cart

- .gitignore
- client/components/order-form.js
- client/components/user-home.js
- client/store/order.js
- server/api/users.js
- server/auth/index.js
> feat: order history available for logged in users

- client/components/cart.js
- client/components/order-form.js
> feat: added default shipping method

- client/components/AllPlants.js
- client/components/SinglePlant.js
- client/routes.js
- package-lock.json
- package.json
- webpack.config.js
> feat: toastify added and add item in cart works

- client/components/user-home.js
> fix: order history includes plant qty

- client/components/SingleCartItem.js
- client/components/cart.js
- client/components/navbar.js
- client/components/order-form.js
- public/style.css
added styling to the cart and order form
> #83 styling forms and cart

- client/app.js
- client/components/SinglePlantView.js
Added toast to single plant view
> #100 toast continue

- client/components/AllPlants.js
- client/components/SinglePlantView.js
toast should work better now with single plant!
removed second toastcontainer provider in the allplant view
> fix: toast works for single plant

- client/components/AllPlants.js
- client/components/SinglePlant.js
- client/components/SinglePlantView.js
toast on bottom to not interfere with navbar
> fix: toast is on bottom

- client/components/auth-form.js
- client/components/confirmationForm.js
- client/components/user-home.js
- public/style.css
> feat: styled auth form

- client/components/auth-form.js
- client/components/splash.js
- public/index.html
> #101 styling

- client/components/navbar.js
- public/style.css
navbar - conditional fixed
styled bg img
> fix: navbar link works

- server/auth/index.js
user security
deleted graceshopper folder
> fix: destructured reqbody for signup

- public/style.css
> fix: column width

- client/components/SinglePlant.js
- client/components/order-form.js
- client/components/splash.js
- client/store/cart.js
- package.json
- server/api/orders.js
> copyedited frontend

- README.md
- client/store/order.js
- server/api/orders.js
- server/auth/index.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/plant.js
- server/db/models/user.js
Removed unnecessary comments and console.logs, and added links to README.
> #103 copyedit server
